# Generated by Django 5.2.5 on 2025-12-28 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('certificate_type', models.CharField(choices=[('barangay_clearance', 'Barangay Clearance'), ('residency', 'Certificate of Residency'), ('indigency', 'Certificate of Indigency'), ('good_moral', 'Good Moral Character'), ('business_clearance', 'Business Clearance')], max_length=50)),
                ('purpose', models.TextField()),
                ('proof_photo_url', models.URLField(blank=True, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, max_length=50, null=True)),
                ('business_nature', models.CharField(blank=True, max_length=255, null=True)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('employees_count', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending Verification'), ('paid', 'Paid'), ('failed', 'Failed Payment Verification')], default='unpaid', max_length=20)),
                ('payment_mode', models.CharField(blank=True, choices=[('gcash', 'GCash'), ('counter', 'Pay-on-the-Counter')], max_length=20, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('claim_status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready for Claim'), ('claimed', 'Claimed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='certificate_user_id_c8a39c_idx'), models.Index(fields=['payment_status'], name='certificate_payment_ffe4fe_idx'), models.Index(fields=['certificate_type'], name='certificate_certifi_f836dc_idx')],
            },
        ),
    ]
