# Generated by Django 5.2.5 on 2025-12-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_certificaterequest_claim_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificaterequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='CertificateRequest',
        ),
        migrations.DeleteModel(
            name='IncidentReport',
        ),
    ]
