# Generated by Django 5.2.5 on 2025-12-28 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('incident_type', models.CharField(choices=[('Theft', 'Theft'), ('Assault', 'Assault'), ('Vandalism', 'Vandalism'), ('Disturbance', 'Disturbance'), ('Other', 'Other')], max_length=50)),
                ('place', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Investigation', 'Under Investigation'), ('Mediation Scheduled', 'Mediation Scheduled'), ('Resolved', 'Resolved')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='reports_inc_user_id_3b1e93_idx'), models.Index(fields=['status'], name='reports_inc_status_24c31e_idx')],
            },
        ),
    ]
